export const testData = [
  {
    seat_id: 1,
    seatNum: 4,
    block: 1,
    price: 3000,
    bookingStatus: "FREE",
  },
  {
    seat_id: 12,
    seatNum: 3,
    block: 1,
    price: 3000,
    bookingStatus: "FREE",
  },
  {
    seat_id: 3,
    seatNum: 1,
    block: 1,
    price: 3000,
    bookingStatus: "FREE",
  },
  {
    seat_id: 11,
    seatNum: 2,
    block: 1,
    price: 3000,
    bookingStatus: "CLOSED",
  },
  {
    seat_id: 9,
    seatNum: 5,
    block: 1,
    price: 3000,
    bookingStatus: "BOOKED",
  },
  {
    seat_id: 7,
    seatNum: 6,
    block: 1,
    price: 3000,
    bookingStatus: "FREE",
  },
  {
    seat_id: 6,
    seatNum: 7,
    block: 2,
    price: 3000,
    bookingStatus: "BOOKED",
  },
  {
    seat_id: 8,
    seatNum: 8,
    block: 2,
    price: 3000,
    bookingStatus: "BOOKED",
  },
  {
    seat_id: 4,
    seatNum: 9,
    block: 2,
    price: 3000,
    bookingStatus: "BOOKED",
  },
  {
    seat_id: 5,
    seatNum: 10,
    block: 2,
    price: 3000,
    bookingStatus: "BOOKED",
  },
  {
    seat_id: 2,
    seatNum: 11,
    block: 2,
    price: 3000,
    bookingStatus: "CLOSED",
  },
  {
    seat_id: 10,
    seatNum: 12,
    block: 2,
    price: 3000,
    bookingStatus: "CLOSED",
  },
];
